// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAENHrEXlpusf9EbrxinfAmnBiJMMPYrT4',
    appId: '1:1092131483187:android:b7cdfa16e7c454a44cbd46',
    messagingSenderId: '1092131483187',
    projectId: 'zaga-7b250',
    storageBucket: 'zaga-7b250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE34P6KDXU1GK1KJwBA9MoWTAvjvnlAJ4',
    appId: '1:1092131483187:ios:d6c5e6f2170a2fb44cbd46',
    messagingSenderId: '1092131483187',
    projectId: 'zaga-7b250',
    storageBucket: 'zaga-7b250.appspot.com',
    androidClientId: '1092131483187-cauhm6i5df92ruuhlp49qg2vbu614bt8.apps.googleusercontent.com',
    iosClientId: '1092131483187-c0celc5ptb3f4mpqlpordi492uqmtq32.apps.googleusercontent.com',
    iosBundleId: 'com.iqonic.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE34P6KDXU1GK1KJwBA9MoWTAvjvnlAJ4',
    appId: '1:1092131483187:ios:c4d2eae39019b7284cbd46',
    messagingSenderId: '1092131483187',
    projectId: 'zaga-7b250',
    storageBucket: 'zaga-7b250.appspot.com',
    androidClientId: '1092131483187-cauhm6i5df92ruuhlp49qg2vbu614bt8.apps.googleusercontent.com',
    iosClientId: '1092131483187-6cd7nsfb2ckleo5a8ufphsau1h0nabns.apps.googleusercontent.com',
    iosBundleId: 'com.zaga.maroc',
  );

}